name = "musakone_backend"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.68.1"
gleam_http = ">= 4.3.0"
gleam_json = ">= 3.1.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
mist = ">= 5.0.4"
envoy = ">= 1.1.0"
cors_builder = ">= 2.0.7"
gleam_time = ">= 1.6.0 and < 2.0.0"
parrot = ">= 2.1.3 and < 3.0.0"
sqlite3 = ">= 1.1.15 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
sqlight = ">= 1.0.3 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0"
